name: Release

on:
  push:
    branches:
      - "master"
      
jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore OsuCatchViewer
      
    - name: Build x86
      run: dotnet build OsuCatchViewer -c Release /p:Platform=x86 --no-restore

    - name: Create x86 release.zip
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'release.zip'
        directory: 'OsuCatchViewer/bin/x86/Release/net8.0-windows7.0/win-x86/'

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "latest"
        title: release
        files: |
          OsuCatchViewer/bin/x86/Release/net8.0-windows7.0/win-x86/release.zip
